(ql:quickload "tikz-helper")
(in-package :tikz-helper)
(defparameter *plotting-dir* "/home/haavagj/src/tikz-helper/")

(defun make-random-list (size)
  (let ((rands nil))
    (dotimes (i size)
      (push (- (random 1.0d0) 0.5) rands))
    rands))

(with-tikz-plot (tikz (concatenate 'string *plotting-dir* "test-graph.tex") 10 5 0 10 0 20)
  (draw-plottingarea-rectangle tikz)
  (clip (tikz)
    (draw-graph tikz (make-range 0 1 10) (mapcar #'+ (make-range 0 2 10) (make-random-list 11)) "blue" "blue,fill=blue")
    (mapcar (lambda (x y err) (draw-profilepoint tikz x y err "draw=red,fill=red"))
	    (make-range 0 1 10)
	    (mapcar #'- (make-range 20 -2 10) (make-random-list 11))
	    (make-range 0.5 0 10))
    (draw-legend-line tikz 7 2.0 1 "Expected" "thick,dotted" "" "")
    (draw-legend-line tikz 7 2.8 1 "Graph" "blue" "blue,fill=blue" "")
    (draw-legend-line tikz 7 2.4 1 "Profile" "red" "red,fill=red" ""))
  (draw-axis-ticks-x-transformed tikz (make-range 0 1 10) 1)
  (draw-axis-ticks-y-transformed tikz (make-range 0 2 10) 1)
  (draw-line tikz 0 0 10 5 "thick,dotted")
  (draw-line tikz 0 5 10 0 "thick,dotted")
  (draw-plottingarea-rectangle tikz)
  (draw-node tikz 5 4.5 "Noisy lines" ""))

(with-tikz-plot (tikz (concatenate 'string *plotting-dir* "test-histo1.tex") 10 5 0 10 0 20)
  (clip (tikz)
    (draw-histogram-top tikz (make-histogram 0 1 (mapcar (lambda (x) (+ (* 10 x) 10)) (make-random-list 10))) "blue"))
  (draw-axis-ticks-x-transformed tikz (make-range 0 1 10) 1)
  (draw-axis-ticks-y-transformed tikz (make-range 0 2 10) 1)
  (draw-plottingarea-rectangle tikz)
  (draw-line tikz 0 2.5 10 2.5 "thick,dotted")
  (draw-tikz-node tikz 10 2.5 "Mean" "right")
  (draw-legend-line tikz 0.5 4.5 1 "Outlined histogram" "blue" "" ""))
 
(with-tikz-plot (tikz (concatenate 'string *plotting-dir* "test-histo2.tex") 10 5 0 10 0 20)
  (clip (tikz)
    (let ((histo (make-histogram 0 1 (mapcar (lambda (x) (+ (* 10 x) 10)) (make-random-list 10)))))
      (draw-histogram tikz  histo "draw=blue!20,fill=blue!20")
      (draw-histogram-top tikz histo "blue!80!black"))
    (draw-histogram-top tikz (make-histogram 0 1 (mapcar (lambda (x) (+ (* 10 x) 10)) (make-random-list 10))) "ultra thick, red"))
  (draw-axis-ticks-x tikz (tikz-transform-x tikz (make-range 0.5 1 9)) (make-range 0 1 9) t 2)
  (draw-axis-ticks-y-transformed tikz (make-range 0 2 10) 1)
  (draw-line tikz 0 2.5 10 2.5 "thick,dotted")
  (draw-tikz-node tikz 10 2.5 "Mean" "right")
  (draw-plottingarea-rectangle tikz)
  (draw-legend-rectangle tikz 0.5 4.5 1 0.2 "Filled histogram" "blue!80!black" "draw=blue!20,fill=blue!20" "")
  (draw-legend-line tikz 0.5 4.1 1 "Outlined histogram" "ultra thick,red" "" ""))

